version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres_db_29uv_user:Gmuj5h34DoRyzurZk9CSFBhDDENeNqyr@dpg-cv7of2ogph6c73962s6g-a/postgres_db_29uv"
      TEST_DATABASE_URL: "postgresql://postgres_user:postgres_password@db:5432/chatdb_test"
    depends_on:
      - db  # Ensure the database starts before the web service

  db:
    image: postgres:15  # Use the latest stable PostgreSQL version
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      CHATDB_TEST: chatdb_test
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Named volume for persistent storage
